# choose starting image @ tensorflow:1.15
FROM tensorflow/tensorflow:1.15.2-py3-jupyter

LABEL "maintainer"="Alin CHIS" "email"="alin.d.chis@gmail.com"


# RUN apt-get update && apt-get install -y texlive

# add npm packages
RUN npm install --global --unsafe --silent \
#   body-parser \
#   cookie-parser \
#   debug \
#   express \
#   morgan \
#   pug \
#   serve-favicon \
  pg \
  pg-hstore \
#   babel-cli \
#   node-latex \
#   nodemon \
#   fs \
  sequelize \
  sequelize-cli

# more stuff...

# environment variables


# add symlinks


# start command
